- build.sh
>  연관된 이슈를 적어주세요.
#0
> 작업한 내용을 적어주세요
깃허브 액션 초기세팅
> #0 [feat] : 초기세팅

- build.sh
>  연관된 이슈를 적어주세요.
#0
> 작업한 내용을 적어주세요
깃허브 액션 초기세팅
> #0 [feat] : main에 머지

- src/App.tsx
>  연관된 이슈를 적어주세요.
#0
> 작업한 내용을 적어주세요
깃허브 액션 초기세팅
> #0 [chore] : 초기 세팅 실험

- package-lock.json
- package.json
- src/App.tsx
> #0 [feat] : axios 설치

- package-lock.json
- package.json
- src/App.tsx
- src/Router.tsx
- src/components/common/button/Button.tsx
- src/components/common/input/Input.tsx
- src/components/common/modal/Modal.tsx
- src/components/layout/footer/Footer.tsx
- src/components/layout/header/Header.tsx
- src/components/layout/sidebar/Sidebar.tsx
- src/index.css
- src/pages/chatPage/ChatPage.tsx
- src/pages/homePage/HomePage.tsx
- src/pages/myPage/MyPage.tsx
- src/pages/oauthPage/OauthPage.tsx
- src/pages/skillArchivePage/SkillArchivePage.tsx
> [feat] : 폴더 구조, router 임시 생성

- src/components/common/bottomSheet/BottomSheetStyle.tsx
- src/components/common/list/ListStyle.tsx
- src/components/common/modal/BasicModalStyle.tsx
- src/components/common/modal/DetailModalStyle.tsx
- src/components/editProfile/EditProfileStyle.tsx
- src/components/home/content/ContentStyle.tsx
- src/components/home/header/HeaderStyle.tsx
- src/components/home/sheetItem/SheetItemStyle.tsx
- src/components/layout/tabBar/TabBarStyle.tsx
- src/components/list/header/HeaderStyle.tsx
- src/components/my/profile/ProfileStyle.tsx
- src/components/my/settings/SettingsStyle.tsx
- src/components/report/content/ContentStyle.tsx
- src/pages/loginSuccessPage/LoginSuccessPageStyle.tsx
- src/pages/myPage/MyPage.tsx
- src/pages/skillArchivePage/SkillArchivePage.tsx
#35 
- 리팩토링 목적 : global로 정의한 h1~h6와 관련한 font들 적용 완료했습니다! 
> [refactor] : global font 적용

- src/components/chat/ChatBox.Style.ts
- src/pages/memoPage/MemoPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.tsx
- src/utils/dateUtils.ts
#47 
- 채팅 페이지 입력박스 outline 제거
- 날짜 계산하는 getFormattedDate 함수 utils에 분리
> [refactor] 코드 리뷰 반영 리팩토링 2

- .gitignore
- src/api/Oauth.ts
> [refactor] : 소셜 로그인 base URL을 환경 변수로 설정

- src/pages/recordCompletePage/RecordCompletePage.tsx
> [refactor] : isClicked 사용

- vercel.json
> [hotfix] : vercel 404 오류

- src/api/Oauth.ts
> 리프레쉬 토큰 오류 해결

- src/components/common/input/Input.Style.ts
- src/components/common/modal/DetailModal.Style.ts
- src/components/common/selectbox/SelectBox.Style.ts
- src/components/layout/tabBar/TabBar.Style.ts
- src/components/my/profile/Profile.Style.ts
- src/components/my/profile/Profile.tsx
- src/components/my/settings/SettingItem.Style.ts
- src/components/my/settings/Settings.Style.ts
- src/pages/editProfile/EditProfilePage.Style.ts
- src/pages/myPage/MyPage.Style.ts
- src/pages/myPage/MyPage.tsx
#60 
마이페이지 UI 수정된 부분 완료했습니다. 
1. 탭바는 다른 페이지 다 완성 후 마지막에 할 예정입니다!
2. 닉네임에 1-10자 안내 문구와, 1/10의 필요성이 있을까...? 에러메세지 있을 경우 이게 위치가 애매해져가지고,, 그냥 placeholder로 안내문구 하고 10글자 정도는 안알려도 되지 않을까 싶은 마음입니당.. ㅎㅎ
> [refactor] : 마이 페이지 UI 수정 부분 반영 완료

- src/components/layout/header/Header.style.ts
- src/components/layout/header/Header.tsx
- src/components/my/profile/Profile.tsx
- src/pages/myPage/MyPage.Style.ts
- src/pages/myPage/MyPage.tsx
#64
- 마이 페이지에 사이드바 적용했습니다! 
- 마이페이지 API 연동 부분 다 주석처리해둘게용!
> [feat] : 마이 페이지 사이드바 적용

- src/components/common/chip/CategoryChip.Style.ts
- src/components/common/chip/Chip.Style.ts
- src/components/common/sideBar/SideBar.tsx
- src/components/list/content/Content.Style.ts
- src/components/list/content/Content.tsx
- src/components/list/header/Header.Style.ts
- src/components/list/header/Header.tsx
- src/pages/listPage/ListPage.Style.ts
- src/pages/listPage/ListPage.tsx
- src/pages/myPage/MyPage.Style.ts
> [feat] : 경험 리스트 페이지 UI 수정 반영

- src/components/common/bottomSheet/BottomSheet.Style.ts
- src/components/common/bottomSheet/BottomSheet.tsx
- src/components/common/bottomSheet/EditBottomSheet.Style.ts
- src/components/common/bottomSheet/EditBottomSheet.tsx
- src/components/common/bottomSheet/FolderBottomSheet.Style.ts
- src/components/common/bottomSheet/FolderBottomSheet.tsx
- src/components/common/bottomSheet/RecordBottomSheet.Style.ts
- src/components/common/bottomSheet/RecordBottomSheet.tsx
#79 
- BottomSheet 수정
역량 모아보기에서의 BottomSheet 적용을 위해 리팩토링하게 되었습니다. 
기존 BottomSheet에 있던 header를 각각의 BottomSheet로 적용하고 기본 BottomSheet에서는 뺐습니다!(그냥 껍데기만을 만듦!!)
> [refactor] : BottomSheet 수정

- src/components/common/bottomSheet/BottomSheet.tsx
- src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.Style.ts
- src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.tsx
- src/components/common/bottomSheet/reportBottomSheet/Textarea.Style.ts
- src/components/common/bottomSheet/reportBottomSheet/Textarea.tsx
- src/components/layout/tabBar/TabBar.tsx
- src/components/report/content/Content.tsx
- src/pages/reportPage/ReportPage.tsx
> [feat] : 역량 모아보기 편집 바텀시트 구현

- src/components/common/selectbox/SelectBox.tsx
- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
> #82 [feat] : 메모 기록 페이지 UI 수정 반영

- vite.config.ts
> [chore] : 배포 환경을 위한 vite.config.js 수정

- .github/workflows/main.yml
> [fix] : yml 파일 수정

- .github/workflows/main.yml
- build.sh
> [fix] : build 파일 수정

- index.html
- src/components/layout/tabBar/TabBar.tsx
- src/pages/reportPage/ReportPage.tsx
> #92 [refactor] : 탭바 수정

- src/components/folder/Folder.Style.ts
- src/components/list/header/Header.Style.ts
- src/pages/folderPage/FolderPage.tsx
#92 
- background, box-shadow 변경
> #92 [refactor] : background, box-shadow 변경

- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
> #92 [refactor] : 아이콘 수정

- src/api/Home.ts
- src/components/home/content/Content.tsx
- vite.config.ts
> #39 [feat] : 홈 페이지 API 연동

- src/components/chat/ChatBox.Style.ts
- src/components/chat/ChatBox.tsx
- src/components/chat/ChatBubble.tsx
- src/components/chat/LodingDot.Style.ts
- src/components/chat/LodingDots.tsx
- src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.Style.ts
- src/components/editProfile/EditProfile.tsx
- src/pages/chatPage/ChatPage.tsx
- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.Style.ts
- src/pages/recordCompletePage/RecordCompletePage.tsx
#92 
1.  탭바
2.  폴더 페이지 플러스 버튼
3.  이전 버튼이 없는 경우
4.  편집 바텀 시트 높이 수정
5.  새폴더 추가 선택박스 -> 칩
6.  메모기록 글자 수 표시
7.  채팅 버튼 색깔 변경
8.  채팅 로딩 중
> #92 [refactor] : 스텝업데이 수정 사항 반영

- package-lock.json
- package.json
- src/components/report/skill/SkillData.ts
- src/components/report/skill/SkillGraph.Style.ts
- src/components/report/skill/SkillGraph.tsx
- src/components/report/skill/SkillList.Style.ts
- src/components/report/skill/SkillList.tsx
- src/pages/keywordPage/KeywordPage.tsx
#98 
- 역량 리스트 컴포넌트 생성
- 역량 그래프 컴포넌트 생성 (rechart 라이브러리 이용)
- SkillGraph.tsx
- SkillList.tsx
- 컴포넌트 이름이 기존 컴포넌트 이름과 비슷해서 헷갈리는 것 같기도 합니다... 좋은 의견 있으시면 공유 부탁드립니다!!
- 현재 그래프 UI가 디자인에서 나온 것과 다른데 완전히 똑같이 만드는 것이 가능할지 잘 모르겠습니다 ㅠㅠ 일단 이건 차차 더 찾아보고 리팩토링 하겠습니당..
- rechart 라이브러리가 원하는 영역 옆에 글자를 넣을 때 html이 아니라 svg로 넣게 됩니다 (html로 시도해봤으나 좌표 설정이 잘 안됨...) 그래서 이 부분 괜찮을지..! 
- +) (하단에 글 작성 플로팅버튼이 여기서도 계속 떠있는 거 맞나요..?! 헷갈..)
> #98 [feat] : 역량 그래프 UI 구현

- src/api/Home.ts
#39 
- 홈페이지 API 연동 기존 api에서 withCredentials : true 설정이 되어있어서 제거 했습니다. 
- 주석 추가했어용!
> [refactor] : 홈 페이지 API 연동 refactor

- src/api/My.ts
- src/components/common/modal/ConfirmModal.tsx
- src/components/my/profile/Profile.tsx
- src/pages/editProfile/EditProfilePage.tsx
- src/pages/myPage/MyPage.tsx
#49 
[feat] : 마이페이지 API 연동
- [8.1] 마이페이지 조회
- [8.2] 로그아웃
- [8.3] 내 정보 수정
> 닉네임 or 소속 변경 둘 중 하나만 해도 가능 !! 
- [8.4] 회원 탈퇴
- 우선 에러 alert 처리 했는데 이 부분 기획에 요청해서 모달을 할지 ? 토스트를 할지 등등 고민해보면 좋을 것 같습니다!
> [feat] : 마이페이지 API 연동

- src/api/Oauth.ts
- src/api/instance.ts
#11 
- 액세스 토큰이랑 리프레시 토큰이 아직 완료되지 않아서 잘 되는 건지 확인할 방법이 없다...! 그래서 일단 전체 회의때 백한테 리프레시 토큰 만료 기간을 좀 줄여달라고 해볼까..?
> #11 [feat] : 1.3 액세스 토큰 재발급 요청 인터셉터 처리

- src/api/Analysis.ts
- src/components/common/bottomSheet/FolderBottomSheet.tsx
- src/components/common/bottomSheet/FolderChangeBottomSheet.tsx
- src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.Style.ts
- src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.tsx
- src/components/common/bottomSheet/reportBottomSheet/Textarea.Style.ts
- src/components/common/selectbox/SelectBox.tsx
- src/components/keyword/keywordSkill/KeywordSkill.tsx
- src/components/report/content/Content.tsx
- src/pages/folderPage/FolderPage.tsx
- src/pages/memoPage/MemoPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.tsx
- src/pages/reportPage/ReportPage.tsx
- src/types/Analysis.ts
#106 , #108 
> 무한스크롤까지 완료!
- 새폴더 추가하기랑 폴더 변경하기를 원래 하나의 FolderBottomSheet로 했는데 이러면 안에 API 연동 로직이 관련없는 것들이 들어가서 그냥 둘을 분리하였습니다! (추후 사용하다가 문제 생기면 말해주세용!)
- 중복되는 타입은 types 폴더에 묶어놨습니당!
> [feat] : 역량 분석 쪽 API 연동 완료 !!!!!! 

- src/App.tsx
- src/api/Home.ts
- src/api/instance.ts
- src/components/common/modal/BasicModal.tsx
- src/components/common/modal/ConfirmModal.tsx
- src/components/home/header/Header.tsx
- src/components/keyword/header/KeywordHeader.tsx
- src/components/list/header/Header.tsx
- src/components/report/content/Content.tsx
- src/pages/listPage/ListPage.tsx
- src/pages/loginPage/SigningIn.tsx
- src/pages/myPage/MyPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.tsx
- src/pages/registerPage/SignUpPage.tsx
> [feat] : 닉네임 로컬스토리지 저장 후 적용

- .github/workflows/main.yml
- build.sh
> [feat] : MOAMOA로 변경

- src/Router.tsx
- src/components/keyword/keywordSkill/KeywordSkill.tsx
- src/components/list/content/Content.tsx
- src/components/report/content/Content.tsx
- src/pages/keywordPage/KeywordPage.tsx
- src/pages/listPage/ListPage.tsx
#117 
플로팅 버튼 수정 및 채팅 다시보기 페이지 이동 수정
> [feat] : 플로팅 버튼 수정 및 채팅 다시보기 페이지 이동 수정

- src/Router.tsx
- src/api/Memo.ts
- src/components/report/content/Content.tsx
- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
#51 
[4.1] 메모 기록 세부 조회
[4.2] 메모 임시 저장 조회
[4.3] 메모 임시 저장하기
[4.4] 경험 기록하기
- 4.1
> #51 [feat] : 메모 페이지 api 연동

- src/App.Style.ts
- src/App.tsx
- src/components/common/bottomSheet/RecordBottomSheet.tsx
- src/components/common/button/FloatingButton.Style.ts
- src/components/common/chip/Chip.Style.ts
- src/components/common/list/List.Style.ts
- src/components/common/sideBar/SideBar.style.ts
- src/components/common/sideBar/SideBar.tsx
- src/components/common/sideBar/SideBarItem.tsx
- src/components/home/content/Content.Style.ts
- src/components/home/content/Content.tsx
- src/components/home/header/Header.Style.ts
- src/components/home/header/Header.tsx
- src/components/home/sheetItem/SheetItem.Style.ts
- src/components/home/sheetItem/SheetItem.tsx
- src/components/layout/header/Header.style.ts
- src/pages/homePage/HomePage.Style.ts
- src/pages/homePage/HomePage.tsx
- src/styles/theme.ts
#122, #124 
1. PC 버전 SideBar
2. 홈페이지 UI 구현
1. 최근 생성된 경험의 수가 달라지면 다시 한번 홈페이지 UI가 괜찮은지 확인할 예정입니다!
2. 모바일에서만 보이고 PC에서는 안보이는거 display : none 했는데 더 좋은 방법이 있다면 추천 부탁드립니다!
> [feat] : PC 버전 SideBar 및 홈페이지 UI 구현

- src/api/Chat.ts
- src/api/Graph.ts
- src/api/Memo.ts
- src/pages/chatPage/ChatPage.tsx
- src/pages/loginSuccessPage/LoginSuccessPage.tsx
- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
- src/pages/oauthPage/OauthPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.tsx
#52 
- 채팅 다시보기 / 임시 저장 채팅 다시보기 로직 각각 구현
- [3.5] 경험 요약하기 재요청 처리
- 가이드 버튼 로직 수정
> #52 [feat] : 채팅 페이지 api 연동 완료

- src/components/common/sideBar/SideBar.style.ts
- src/components/common/sideBar/SideBarItem.tsx
- src/hooks/useNicknameValidation.ts
- src/pages/registerPage/SignUpPage.tsx
#137
[feat] :사이드 바 호버 했을 떄 색깔 변화 및 애니메이션 추가
> [feat] : 사이드 바 호버 했을 때 색깔 변화 및 애니메이션 추가, 닉네임 수정

- src/pages/chatPage/ChatPage.tsx
- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
#129 
- 메모기록 qa 반영
- 채팅기록 qa 반영
> #129 [refactor] : QA 수정 사항 일부 반영 2

- src/components/common/list/List.Style.ts
- src/components/keyword/keywordList/KeywordList.Style.ts
> [fix] : 제목이 매우 긴 경우 처리

- src/components/common/list/List.Style.ts
- src/components/keyword/keywordList/KeywordList.Style.ts
> [refactor] : 리스트의 max-width 너비 고정

- index.html
- src/components/common/popup/FolderChangePopUp.tsx
- src/pages/reportPage/ReportPage.tsx
- src/types/Analysis.ts
#149
1차 QA 수정 요구 사항 반영
1. 폴더 변경 안되는 문제 해결
2. 폴더 변경 시 default로 기존 폴더 이름 나오기 
> [fix] : 1차 QA 수정 요구 사항 반영

- src/components/chat/ToastMessage.Style.ts
- src/components/common/popup/FolderChangePopUp.tsx
- src/pages/reportPage/ReportPage.tsx
#151 
- 토스트 애니메이션 아래에서 위로만 올라오게 변경
- 역량 레포트에서 폴더 변경하고 나서 토스트 적용
- 역량 레포트에서 내용 수정하고 나서 토스트 적용
- 적용을 고민해야하는 부분
1. 역량 레포트 삭제 시 토스트 적용
- 고민 이유 : 역량 레포트를 접근할 수 있는 곳은 홈, 경험, 키워드 페이지 하지만 각각의 곳에서 showToast를 관리해야한다... 
2. 폴더 관리 페이지에서 폴더 추가하고 삭제하기 
- 고민 이유 : 이미 시각적으로 폴더가 생성되고 삭제된게 눈에 보임..
> [feat] : 토스트 애니메이션 수정 및 적용

- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.Style.ts
- src/pages/recordCompletePage/RecordCompletePage.tsx
> [feat] : 메모 & 경험 기록 완료 페이지 PC UI

- src/components/keyword/skill/SkillGraph.Style.ts
- src/components/keyword/skill/SkillList.Style.ts
> [refactor] : 역량 그래프 & 리스트 정렬 수정

- src/App.tsx
> [fix] : 동적 라우트에 대한 SideBar 표시 로직 수정

- src/components/chat/ChatBox.Style.ts
> #177 [fix] : 채팅 input 폰트 사이즈 수정

- src/App.tsx
- src/Router.tsx
- src/assets/icons/AddFolderIcon.svg
- src/components/keyword/header/KeywordHeader.style.ts
- src/components/keyword/skill/SkillGraph.tsx
- src/components/keyword/skill/SkillList.Style.ts
- src/components/keyword/skill/SkillList.tsx
- src/hooks/useValidatePathId.ts
- src/pages/chatPage/ChatPage.tsx
- src/pages/keywordPage/KeywordPage.Style.ts
- src/pages/memoPage/MemoPage.Style.ts
- src/pages/memoPage/MemoPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.Style.ts
- src/pages/registerPage/SignUpPage.Style.ts
- src/pages/reportPage/ReportPage.tsx
#177 
- 메모 기록 최소 글자수 50자로 변경
- 역량 그래프 상위 7개 항목만 노출
- 메모 다시보기 시 폴더 조회 기능 추가
- 존재하는 경로인지 확인하는 useValidatePathId 훅 생성
- 자잘한 스타일 수정
> [fix] : QA 수정 요청 사항 반영

- src/components/common/sideBar/SideBarItem.tsx
- src/components/home/sheetItem/SheetItem.Style.ts
> [fix] : 자잘한 스타일 수정

- src/pages/onboardingPage/OnboardingPage.Style.ts
- src/pages/onboardingPage/OnboardingPage.tsx
> #179 [fix] : 온보딩 페이지 수정

- src/components/my/settings/Settings.tsx
- src/pages/onboardingPage/OnboardingPage.Style.ts
- src/pages/onboardingPage/OnboardingPage.tsx
> [fix] : 온보딩 페이지 이동 수정

- src/components/common/bottomSheet/RecordBottomSheet.tsx
- src/components/common/button/Button.tsx
- src/components/common/button/FloatingButton.Style.ts
- src/components/common/modal/ConfirmModal.tsx
- src/components/common/modal/Modal.tsx
- src/components/common/popup/EditPopUp.Style.ts
- src/components/common/popup/EditPopUp.tsx
- src/components/common/popup/reportPopup/ReportPopUp.tsx
- src/components/editProfile/EditProfile.tsx
- src/components/folder/Folder.tsx
- src/components/keyword/header/KeywordHeader.tsx
- src/components/keyword/keywordList/KeywordList.tsx
- src/components/keyword/keywordSkill/KeywordSkill.tsx
- src/components/keyword/skill/SkillList.tsx
- src/components/list/content/Content.tsx
- src/components/report/comment/Comment.tsx
- src/components/report/skill/Skill.tsx
> [refactor] : 자잘한 코드 스타일 수정

- index.html
- src/components/chat/ChatBox.Style.ts
- src/components/chat/ChatBox.tsx
- src/components/chat/ChatBubble.tsx
- src/components/chat/GuideButton.Style.ts
#196 
- jsDocs 추가
- cursor pointer 추가
> [refactor] : jsDocs 추가 및 css 수정

- index.html
> [feat] : msclarity 코드 삽입

- index.html
> [chore] : 자잘한 수정

- index.html
- package-lock.json
- package.json
- src/App.tsx
> [feat] : Google Analytics 삽입

- src/pages/oauthPage/OauthPage.tsx
> [fix] : OAuth 카카오 로그인 URL 수정

- package-lock.json
- package.json
- src/App.tsx
- src/utils/ga.ts
#204 
- react-ga 설치
- util에 ga.ts 생성
> [feat] : react-ga4 적용

- package-lock.json
- package.json
- src/App.tsx
- src/pages/oauthPage/OauthPage.tsx
- src/utils/ga.ts
> #202 [feat] : react-ga4 적용

- src/components/home/content/Content.Style.ts
- src/components/home/header/Header.Style.ts
- src/components/layout/tabBar/TabBar.Style.ts
- src/components/layout/tabBar/TabBar.tsx
- src/pages/chatPage/ChatPage.tsx
> [feat] : 디자인 수정 사항 반영

- src/components/home/content/Content.tsx
> [feat] : 카드칩 폴더 수정

- index.html
- src/api/Chat.ts
- src/api/Record.ts
- src/components/chat/ChatBox.tsx
- src/components/home/content/Content.tsx
- src/components/list/content/Content.tsx
- src/pages/chatPage/ChatPage.tsx
- src/pages/feedbackPage/DislikeOptionModal.tsx
- src/pages/feedbackPage/FeedbackModal.tsx
- src/pages/homePage/HomePage.tsx
- src/pages/memoPage/MemoPage.tsx
- src/pages/recordCompletePage/RecordCompletePage.tsx
- src/pages/reportPage/ReportPage.tsx
- src/utils/ga.ts
#213 
- 만족도 조사 기능 구현
- 채팅 입력 500자 제한
- 토스트 메세지 적용
- alert 문구 & UX라이팅 수정
> [feat] : 만족도 조사 기능 구현

- public/service-worker.js
- src/serviceWorkerRegistration.ts
- src/styles/global.ts
- vite.config.ts
- PWA IOS 하단 여백 제거
- 자동 업데이트 기능 추가
> [feat] : PWA 자동 업데이트 기능 추가 & IOS 하단 여백 제거 

- src/components/chat/ChatBox.Style.ts
- src/components/chat/ChatBox.tsx
#234 
- handleSend 중복 실행 방지 및 메시지 초기화 문제 해결
- 채팅 입력창 placeholder 글자 간격 수정
> [fix] : handleSend 중복 실행 방지 및 메시지 초기화 문제 해결

- src/components/chat/ChatBox.tsx
> fix: 아이폰에서 줄바꿈 안 되는 문제 해결

- src/components/chat/ChatBox.tsx
> [fix] : PC 엔터 전송 안 되는 문제 해결

- src/pages/registerPage/SignUpPage.Style.ts
> [style] : 로그인 화면 드롭다운 가리는 문제 해결

- index.html
- src/components/chat/ChatBox.Style.ts
- src/styles/global.ts
#244 
- iOS PWA 전체화면 지원을 위한 viewport-fit=cover 적용
> [refactor] : iOS PWA 전체화면 지원을 위한 viewport-fit=cover 적용

- index.html
> [revert] : iOS PWA 전체화면 지원을 위한 viewport-fit=cover 적용 롤백

- src/components/home/content/Content.tsx
- src/components/keyword/keywordSkill/KeywordSkill.tsx
- src/components/list/content/Content.tsx
- src/pages/listPage/ListPage.tsx
- src/pages/oauthPage/OauthPage.tsx
> [fix] 텅 깜빡임 오류 수정

- src/pages/oauthPage/OauthPage.tsx
> [hotfix] : 잘못된 경로 수정

- index.html
- src/components/chat/ChatBox.Style.ts
> [refactor] : 채팅 입력바 폰트 수정
